name: Deploy release to os2forms-bellcom.devel.dk
on:
  push:
    tags:        
      - '*' 
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        script: |
          whoami
          sh /var/www/os2forms-bellcom.devel.dk/private/os2forms_init/rebuild_installation.sh
